# Generated by Django 5.2.7 on 2025-11-01 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworkerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_worker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mother_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
